# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: twitterscan_topic_ranking
  path.config: "/usr/share/logstash/src/twitterscan_trending_topics.conf"

